#!/bin/bash
# Workflow Disable Script for Stage B Rollback
# Usage: ./scripts/rollback/workflow-disable.sh [workflow-name] [reason]

set -e

WORKFLOW_NAME="$1"
REASON="$2"
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)

if [ -z "$WORKFLOW_NAME" ] || [ -z "$REASON" ]; then
    echo "Usage: $0 <workflow-name> <reason>"
    echo "Example: $0 frontmatter-validation 'High false positive rate'"
    exit 1
fi

WORKFLOW_FILE=".github/workflows/${WORKFLOW_NAME}.yml"
DISABLED_FILE=".github/workflows/${WORKFLOW_NAME}.yml.disabled"

# Check if workflow exists
if [ ! -f "$WORKFLOW_FILE" ]; then
    echo "❌ Workflow file not found: $WORKFLOW_FILE"
    exit 1
fi

# Check if already disabled
if [ -f "$DISABLED_FILE" ]; then
    echo "⚠️ Workflow already disabled: $DISABLED_FILE"
    exit 1
fi

echo "🔄 Disabling workflow: $WORKFLOW_NAME"
echo "📝 Reason: $REASON"

# Disable the workflow
mv "$WORKFLOW_FILE" "$DISABLED_FILE"

# Create rollback log entry
LOG_DIR="08_CHRONICLE/incidents"
LOG_FILE="$LOG_DIR/${TIMESTAMP}_rollback-workflow-disable.md"

mkdir -p "$LOG_DIR"

cat > "$LOG_FILE" << EOF
---
project: Career Intelligence Space
type: rollback_incident
status: active
tags: [rollback, workflow_disable, stage_b, incident]
updated: $(date +%Y-%m-%d)
rollback_type: workflow_disable
workflow_name: $WORKFLOW_NAME
reason: $REASON
timestamp: $TIMESTAMP
---

# Rollback Incident - Workflow Disable

**Date:** $(date +%Y-%m-%d)
**Time:** $(date +%H:%M:%S)
**Rollback Type:** Workflow Disable
**Workflow:** $WORKFLOW_NAME
**Reason:** $REASON

## Actions Taken
- [x] Workflow file renamed: \`$WORKFLOW_FILE\` → \`$DISABLED_FILE\`
- [x] Rollback incident logged: \`$LOG_FILE\`

## Verification Steps
- [ ] Confirm workflow no longer appears in GitHub Actions
- [ ] Verify other workflows still active
- [ ] Check system performance improvement
- [ ] Monitor for new failures

## Next Steps
- [ ] Monitor system health for 24-48 hours
- [ ] Conduct root cause analysis
- [ ] Plan workflow re-enablement or modification
- [ ] Update rollback documentation if needed

## Recovery Plan
**Timeline:** [TO_BE_DETERMINED]
**Actions:**
- [ ] Fix underlying issue
- [ ] Test workflow in staging
- [ ] Re-enable with monitoring
- [ ] Document lessons learned

---
*Generated by rollback automation script*
EOF

echo "✅ Workflow disabled successfully"
echo "📄 Rollback log created: $LOG_FILE"

# Commit the changes
git add "$DISABLED_FILE" "$LOG_FILE"
git commit -m "rollback: disable $WORKFLOW_NAME workflow

Reason: $REASON
Rollback Type: Workflow Disable
Incident Log: $LOG_FILE

This is a Stage B rollback action to address system issues.
See docs/runbooks/STAGE_B_ROLLBACK.md for procedures."

echo "📝 Changes committed to git"
echo "🚀 Ready to push: git push origin [branch-name]"
