---
# Strategic Lenses Configuration
# Career Intelligence Space (CIS) Consultant Lens System
project: Career Intelligence Space
type: configuration
status: active
updated: 2025-09-29
tags: [cis, config, strategic_lenses, consultant_system]
---

# Lens System Status
system_status: active  # active | inactive | maintenance
activation_date: 2025-09-29
version: 1.0.0

# Individual Lens Controls
lenses:
  strategic_analyst:
    status: active
    priority: high
    use_cases: [weekly_reviews, milestone_assessments, strategic_planning]
  
  project_manager:
    status: active
    priority: high
    use_cases: [task_breakdown, timeline_planning, resource_allocation]
  
  systems_engineer:
    status: active
    priority: medium
    use_cases: [technical_bottlenecks, workflow_optimization, automation_gaps]
  
  productivity_coach:
    status: active
    priority: medium
    use_cases: [momentum_assessment, energy_management, workflow_optimization]
  
  venture_designer:
    status: active
    priority: low
    use_cases: [opportunity_mapping, market_positioning, competitive_analysis]

# Usage Guidelines
usage_rules:
  - "Only use lenses when system_status is 'active'"
  - "Check individual lens status before application"
  - "Document lens usage in chronicle entries"
  - "Report issues or improvements via GitHub issues"

# Stage B Rollback Configuration
stage_b_enforcement:
  level: strict  # strict | lenient | disabled
  frontmatter_validation: block  # block | warn_only | disabled
  promotion_gates: required  # required | optional | disabled
  workflow_validation: block  # block | warn_only | disabled
  
  # Rollback triggers and thresholds
  triggers:
    velocity_drop_threshold: 50  # percentage
    pr_failure_threshold: 30     # percentage
    review_completion_threshold: 60  # percentage
    system_health_threshold: 3   # failures per 24h
    
  # Rollback authority levels
  authority:
    automated: true   # Allow automated rollback triggers
    manual: true      # Allow manual rollback decisions
    emergency: true   # Allow emergency rollback override

# Rollback Information
rollback:
  last_stable_version: "stage-a-final"
  rollback_instructions: "See docs/runbooks/STAGE_B_ROLLBACK.md for detailed procedures"
  emergency_contact: "jwade83"
  rollback_log: "08_CHRONICLE/incidents/"
