name: "Frontmatter Autofix"
description: "Normalize frontmatter on changed markdown files"
inputs:
  python-version:
    description: "Python version"
    default: "3.11"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Run normalizer
      shell: bash
      run: |
        python3 scripts/frontmatter_normalize.py

