name: Frontmatter Lint

on:
  pull_request:
    paths:
      - '08_CHRONICLE/**/*.md'
      - '11_FUTURE/**/*.md'
      - 'docs/**/*.md'
      - 'config/archive_schema.yml'
      - 'scripts/lint_frontmatter.py'
  push:
    branches:
      - main
    paths:
      - '08_CHRONICLE/**/*.md'
      - '11_FUTURE/**/*.md'
      - 'docs/**/*.md'
      - 'config/archive_schema.yml'
      - 'scripts/lint_frontmatter.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install pyyaml pytest
      
      - name: Run linter unit tests
        run: pytest -q scripts/tests/test_linter.py
      
      - name: Lint frontmatter
        run: python scripts/lint_frontmatter.py

