name: frontmatter-required
on:
  pull_request:
permissions:
  contents: read
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Front-matter gate
        env:
          FRONTMATTER_STRICT_TAGS: "0"
        run: python3 .github/scripts/frontmatter_gate.py
