name: linkcheck-rerun-on-transient
on:
  workflow_run:
    workflows: ["linkcheck"]
    types: [completed]
permissions:
  actions: write
concurrency:
  group: linkcheck-rerun-${{ github.event.workflow_run.conclusion }}-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true
jobs:
  rerun-if-transient:
    if: >
      ${{
        github.event.workflow_run.name == 'linkcheck' &&
        github.event.workflow_run.conclusion == 'failure' &&
        github.actor != 'github-actions[bot]'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if already retried recently (simple backoff)
        id: backoff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # Simple backoff: check if this workflow run was already retried
          # by looking at the run name/description for retry indicators
          RUN_DESCRIPTION=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} --jq '.display_title // ""' || echo "")
          if echo "$RUN_DESCRIPTION" | grep -qi "retry\|rerun"; then
            echo "Already retried - skipping to prevent storm"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Download logs
        if: steps.backoff.outputs.skip == 'false'
        id: dl
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          curl -fsSL -H "Authorization: Bearer $GH_TOKEN" "${{ github.event.workflow_run.logs_url }}" -o logs.zip
          unzip -p logs.zip | tail -n 2000 > logs.txt || true
          echo "size=$(wc -c < logs.txt)" >> $GITHUB_OUTPUT
      - name: Detect transient errors
        if: steps.backoff.outputs.skip == 'false'
        id: detect
        run: |
          set -euo pipefail
          if grep -Ei '(HTTP 429|502|503|504|ETIMEDOUT|ECONNRESET|temporary failure|rate limit)' logs.txt; then
            echo "transient=true" >> $GITHUB_OUTPUT
          else
            echo "transient=false" >> $GITHUB_OUTPUT
          fi
      - name: Re-run linkcheck once
        if: steps.backoff.outputs.skip == 'false' && steps.detect.outputs.transient == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          curl -fsSL -X POST -H "Authorization: Bearer $GH_TOKEN"             https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/rerun
