name: linkcheck
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

# Prevent multiple linkcheck runs on the same ref
concurrency:
  group: linkcheck-${{ github.ref || github.sha }}
  cancel-in-progress: true

jobs:
  links:
    runs-on: ubuntu-latest
    # Only run in the main repository, not forks
    if: github.repository_owner == 'jwade83'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run linkcheck
        run: python3 .github/scripts/linkcheck.py
