name: linkcheck-rerun-on-transient

on:
  workflow_run:
    workflows: ["linkcheck"]         # must exactly match your linkcheck workflow name
    types: [completed]

permissions:
  actions: write
  contents: read

# One rerun max per commit; never dogpile on the same SHA
concurrency:
  group: linkcheck-rerun-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true

jobs:
  rerun-once-if-transient:
    # HARD GUARDS to prevent loops/noise
    if: >
      github.repository_owner == 'jwade83' &&
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.run_attempt == 1 &&                 # only rerun the FIRST failed attempt
      github.event.workflow_run.event != 'workflow_run' &&          # avoid tail-chasing reruns of reruns
      (github.event.workflow_run.head_branch == 'main' ||           # only important branches
       startsWith(github.event.workflow_run.head_branch, 'release/'))
    runs-on: ubuntu-latest
    steps:
      - name: Decide if it's a transient failure
        id: gate
        run: |
          # Pull summary text to look for classic transient signals
          curl -fsSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}" \
            | jq -r '.conclusion,.name,.head_branch' >/dev/null

          # Heuristic signals we consider "transient"
          # (tune as needed; kept conservative on purpose)
          echo "transient=false" >> "$GITHUB_OUTPUT"

          # Grab jobs list & logs URLs
          jobs_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs"
          jobs_json=$(curl -fsSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "$jobs_url")

          # Look for network-ish failures in job conclusions or summaries
          # You can expand this list as you see patterns (429, timeout, DNS, ECONNRESET, rate limit)
          if echo "$jobs_json" | jq -r '.jobs[]?.steps[]?.name + " " + (.jobs[]?.steps[]?.conclusion // "")' 2>/dev/null | \
             grep -Ei '(timeout|timed out|429|rate.?limit|econnreset|socket hang up|network|dns|temporary|transient)' >/dev/null; then
            echo "transient=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Rerun linkcheck (ONE TIME)
        if: steps.gate.outputs.transient == 'true'
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/rerun
      - name: Summarize action
        run: |
          echo "Rerun considered for run ${{ github.event.workflow_run.id }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Branch: ${{ github.event.workflow_run.head_branch }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Head SHA: ${{ github.event.workflow_run.head_sha }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- First attempt: ${{ github.event.workflow_run.run_attempt == 1 }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Transient: ${{ steps.gate.outputs.transient }}" >> "$GITHUB_STEP_SUMMARY"