name: Link & Anchor Check

on:
  pull_request:
    paths: ["**/*.md"]
  push:
    branches: [main]
    paths: ["**/*.md"]
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Link Checker
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.9.3
        with:
          args: >-
            --no-progress --verbose
            --exclude-mail
            --accept 200,206,429
            --base .
            **/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Create Issue From File (if failures)
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Check Failed
          content-filepath: ./lychee/out.md
          labels: |
            automated
            broken-links
            needs-review

