name: Persistent Voice Notes Processor

on:
  push:
    paths:
      - '08_CHRONICLE/capture_inbox/VOICE_NOTES.md'
  workflow_dispatch:

jobs:
  process-voice-notes:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'VOICE_NOTES')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install pyyaml
          
      - name: Process Voice Notes
        run: |
          # Generate timestamp for new capture
          TIMESTAMP=$(date +%Y%m%d_%H%M)
          
          # Extract current session content
          CURRENT_SESSION=$(grep -A 1000 "## Current Session" 08_CHRONICLE/capture_inbox/VOICE_NOTES.md | grep -A 1000 "\[Use voice-to-text here" | head -n -3 | tail -n +2)
          
          # Check if there's actual content (not just placeholder)
          if echo "$CURRENT_SESSION" | grep -q "\[Use voice-to-text here"; then
            echo "No new content to process"
            exit 0
          fi
          
          # Create new capture file from current session
          cat > "08_CHRONICLE/capture_inbox/raw_${TIMESTAMP}.md" << EOF
          ---
          project: Career Intelligence Space
          type: mobile_capture
          status: raw
          tags: [mobile_capture, field_agent, voice_notes]
          captured_at: $(date +%Y-%m-%d)
          capture_type: voice_notes
          source: github_mobile
          timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
          ---
          
          # Voice Notes Capture
          
          ## Content
          $CURRENT_SESSION
          
          ---
          **Field Agent Voice Notes - ${TIMESTAMP}**
          EOF
          
          # Update VOICE_NOTES.md - move current session to previous notes
          cat > "08_CHRONICLE/capture_inbox/VOICE_NOTES.md" << EOF
          ---
          project: Career Intelligence Space
          type: mobile_capture
          status: active
          tags: [mobile_capture, field_agent, voice_notes, persistent]
          captured_at: $(date +%Y-%m-%d)
          capture_type: voice_notes
          source: github_mobile
          ---
          
          # Voice Notes & Field Notes
          
          ## Current Session
          [Use voice-to-text here - speak your thoughts and they'll appear here]
          
          ---
          
          ## Previous Notes
          ### ${TIMESTAMP}
          $CURRENT_SESSION
          
          ---
          **Field Agent Voice Notes - Persistent Input**
          EOF
          
          echo "✅ Created capture: raw_${TIMESTAMP}.md"
          echo "✅ Updated VOICE_NOTES.md with persistent history"
          
      - name: Process with capture processor
        run: |
          python scripts/capture-processor.py
          
      - name: Commit processed files
        run: |
          git config --global user.email "field-agent@career-intelligence-space"
          git config --global user.name "Field Agent"
          
          git add 08_CHRONICLE/capture_inbox/
          git add 08_CHRONICLE/conversations/lite/
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "feat(voice-notes): process persistent voice notes capture
            
            - Processed current session into timestamped capture
            - Moved current session to previous notes history
            - Reset current session for next voice note
            - Generated lite archive with full Harness compliance
            - Automated by Persistent Voice Notes Processor workflow"
            
            git push origin ${{ github.ref_name }}
          fi
