name: pr-babysitter
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  attach-required-checks:
    runs-on: ubuntu-latest
    # Only run for PR events, not push events
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Wait briefly for checks to appear
        run: sleep 25
      - name: Check statuses for required contexts
        id: probe
        env:
          REPO: ${{ github.repository }}
          SHA:  ${{ github.event.pull_request.head.sha }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          S=$(curl -fsSL -H "Authorization: Bearer $GH_TOKEN"                -H "Accept: application/vnd.github+json"                "https://api.github.com/repos/$REPO/commits/$SHA/status"                | jq -r '[.statuses[]?|select(.context=="links" or .context=="gate")|.state]|join(",")')
          echo "states=$S" >> "$GITHUB_OUTPUT"
      - name: No-op commit to PR branch if required contexts missing
        if: ${{ steps.probe.outputs.states == '' || steps.probe.outputs.states == 'pending' }}
        run: |
          set -euo pipefail
          mkdir -p .github/keep
          printf '
' >> .github/keep/pr-babysitter.keep
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .github/keep/pr-babysitter.keep
          git commit -m "chore(ci): babysitter attach PR-event checks"
          git push origin HEAD:${{ github.head_ref }}
