name: PR Babysitter

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-babysitter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  attach-required-checks:
    name: Attach Required Checks
    runs-on: ubuntu-latest
    # run only for real PR events and not for bot accounts
    if: ${{ github.actor != 'github-actions[bot]' && github.actor != 'dependabot[bot]' }}

    steps:
      - name: Resolve PR context
        id: ctx
        run: |
          echo "sha=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_OUTPUT"
          echo "pr=${{ github.event.pull_request.number }}"   >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Wait briefly for checks to appear
        run: sleep 2

      - name: Check statuses for required contexts
        id: probe
        env:
          REPO: ${{ github.repository }}
          SHA: ${{ steps.ctx.outputs.sha }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          STATUS_JSON=$(curl -fsSL \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/commits/$SHA/status")
          
          STATES=$(echo "$STATUS_JSON" | jq -r '[.statuses[]? | select(.context=="links" or .context=="gate") | .state] | join(",")')
          echo "states=$STATES" >> "$GITHUB_OUTPUT"
          echo "Found states: $STATES"

      - name: No-op commit to PR branch if required contexts missing
        if: ${{ steps.probe.outputs.states == '' || steps.probe.outputs.states == 'pending' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p .github/keep
          echo "." >> .github/keep/pr-babysitter.keep
          
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/keep/pr-babysitter.keep
          git commit -m "chore(ci): babysitter attach PR-event checks"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}