name: reflexive-rollup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'
permissions:
  contents: write
jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run rollup
        run: python .github/scripts/reflexive_rollup.py
      - name: Commit rollup (if changed)
        shell: bash
        run: |
          if git status --porcelain 08_CHRONICLE/weekly_reflexive_rollup_*.md 2>/dev/null | grep -q .; then
            git config user.name "ci-bot"
            git config user.email "actions@github"
            git add 08_CHRONICLE/weekly_reflexive_rollup_*.md
            git commit -m "chore(rollup): weekly reflexive metrics"
            git push
          else
            echo "No changes to commit."
          fi
