name: tag-drift-warn
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  warn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: OOV tag warning (non-blocking)
        run: python3 .github/scripts/tag_drift_warn.py
