name: update-migration-map
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate migration map
        run: |
          set -euo pipefail
          python3 scripts/build_migration_map.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ci/auto-migration-map
          title: "docs: auto-update migration map"
          body: "Automated update of migration map."
          commit-message: "docs: auto-update migration map [skip ci]"
          base: main
          delete-branch: true
