name: Weekly Lens Review Reminder

on:
  schedule:
    - cron: '0 16 * * 5'  # Friday 9:00 AM PT (16:00 UTC)
  workflow_dispatch:
    inputs:
      week_start:
        description: "Week start date (YYYY-MM-DD)"
        required: false
        default: ""
      week_end:
        description: "Week end date (YYYY-MM-DD)"
        required: false
        default: ""

permissions:
  issues: write
  contents: read

env:
  WEEK_START: ${{ github.event.inputs.week_start || '' }}
  WEEK_END: ${{ github.event.inputs.week_end || '' }}

jobs:
  create-weekly-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate week dates
        id: dates
        run: |
          if [ -n "$WEEK_START" ] && [ -n "$WEEK_END" ]; then
            echo "week_start=$WEEK_START" >> $GITHUB_OUTPUT
            echo "week_end=$WEEK_END" >> $GITHUB_OUTPUT
          else
            # Calculate next week's dates (Friday to Friday)
            if [ "$(date +%u)" -eq 5 ]; then
              # If today is Friday, use next week
              week_start=$(date -d "+3 days" +%Y-%m-%d)
              week_end=$(date -d "+9 days" +%Y-%m-%d)
            else
              # Find next Friday
              days_until_friday=$(( (5 - $(date +%u) + 7) % 7 ))
              if [ $days_until_friday -eq 0 ]; then
                days_until_friday=7
              fi
              week_start=$(date -d "+$days_until_friday days" +%Y-%m-%d)
              week_end=$(date -d "+$((days_until_friday + 6)) days" +%Y-%m-%d)
            fi
            echo "week_start=$week_start" >> $GITHUB_OUTPUT
            echo "week_end=$week_end" >> $GITHUB_OUTPUT
          fi

      - name: Create weekly lens review issue
        uses: actions/github-script@v7
        with:
          script: |
            const weekStart = '${{ steps.dates.outputs.week_start }}';
            const weekEnd = '${{ steps.dates.outputs.week_end }}';
            const weekNumber = Math.ceil((new Date(weekStart) - new Date('2025-09-29')) / (7 * 24 * 60 * 60 * 1000)) + 1;
            
            const title = `Weekly Lens Review - Week of ${weekStart}`;
            const body = `## Weekly Strategic Lens Review

            **Week:** ${weekStart} to ${weekEnd}  
            **Stage:** A (Week ${weekNumber} of 6)  
            **Lenses:** Strategic Analyst + Project Manager + Productivity Coach

            ### Checklist

            - [ ] **Strategic Analyst Lens** - Big-picture project review
              - [ ] Status assessment
              - [ ] Milestone tracking
              - [ ] Pain point identification
              - [ ] Opportunity analysis
              - [ ] Strategic gap assessment

            - [ ] **Project Manager Lens** - Task-level execution review
              - [ ] Task inventory
              - [ ] Timeline assessment
              - [ ] Dependencies and blockers
              - [ ] Resource allocation
              - [ ] Risk mitigation
              - [ ] Next actions

            - [ ] **Productivity Coach Lens** - Momentum and energy assessment
              - [ ] Momentum assessment
              - [ ] Energy patterns
              - [ ] Workflow rhythm
              - [ ] Habit formation
              - [ ] Flow state optimization
              - [ ] Sustainable practices

            - [ ] **Chronicle Integration**
              - [ ] Save to \`/08_CHRONICLE/weekly/\` directory
              - [ ] Apply proper frontmatter and tags
              - [ ] Include lens metadata
              - [ ] Update metrics tracking

            - [ ] **Metrics Collection**
              - [ ] Update coverage metrics
              - [ ] Assess quality metrics
              - [ ] Track value metrics
              - [ ] Update Stage A progress

            ### Notes
            [Any specific focus areas or issues to address this week]

            ### Completion
            - [ ] Weekly review completed
            - [ ] Chronicle entry created
            - [ ] Metrics updated
            - [ ] Issue closed

            ---
            *Auto-generated by Weekly Lens Review Reminder*`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['strategic-lenses', 'weekly-review', 'stage-a'],
              assignees: ['jwade83']
            });

      - name: Log completion
        run: |
          echo "Weekly lens review reminder created for week of ${{ steps.dates.outputs.week_start }}"
